name:                parserModules
version:             0.1.0.0
github:              "morning85/parserModules"
author:              "Asa Tomita"
maintainer:          "tomita.asa@is.ocha.ac.jp"
copyright:           "2024 Asa Tomita"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/morning85/parserModules#readme>

dependencies:
- base >= 4.7 && < 5
- nlp-tools
- text
- shelly
- parsec
- unicode-show
- directory >= 1.3.6.0
- yaml >= 0.11.8.0
- bytestring >= 0.10.12.0
- aeson
- filepath
- lightblue
- jsem

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions: OverloadedStrings
  exposed-modules:
  - Parser.KWJA
  - Parser.ABC
  - Parser.JumanKatuyou

executables:
  parserModules-exe:
    main:                callkwja.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parserModules
  printEc :
    main:                printLightblue.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parserModules

tests:
  parserModules-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parserModules
